# serverless.yml

service: apollo-lambda
provider:
  name: aws
  stage: beta
  region: us-east-2
  runtime: nodejs10.x
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: server.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true